package com.chryl.sharding.mapper;

import com.chryl.sharding.entity.Goods;
import com.chryl.sharding.entity.GoodsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    long countByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int deleteByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    List<Goods> selectByExample(GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    Goods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByPrimaryKey(Goods record);
}