package com.chryl.sharding.mapper;

import com.chryl.sharding.entity.MyOrder;
import com.chryl.sharding.entity.MyOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    long countByExample(MyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int deleteByExample(MyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insert(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insertSelective(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    List<MyOrder> selectByExample(MyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    MyOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") MyOrder record, @Param("example") MyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExample(@Param("record") MyOrder record, @Param("example") MyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByPrimaryKeySelective(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByPrimaryKey(MyOrder record);
}