package com.chryl.sharding.mapper;

import com.chryl.sharding.entity.OrderDetail;
import com.chryl.sharding.entity.OrderDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    long countByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int deleteByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    List<OrderDetail> selectByExample(OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Fri Apr 02 11:06:25 CST 2021
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailCriteria example);
}